language: android
sudo: required
jdk:  oraclejdk8
#env:
#  global:
#  - GRADLE_OPTS="Xmx2048m"
branches:
  only:
    - development
    - master

stages:
  - name: compile
    if: tag IS blank
  - name: test
    if: tag IS blank
  - name: release
    if: type = push

before_install:
  - chmod +x gradlew
#  -
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.android/build-cache
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

install: skip

jobs:
  include:
    - name: "Static Analysis"
      stage: compile

      before_script: skip
      script:
        - chmod +x gradlew
        - ./gradlew check --continue --stacktrace --parallel

      after_failure:
        - cat /home/travis/build/CruGlobal/mpdx-android/build/reports/lint-results*.xml
        - cat /home/travis/build/CruGlobal/mpdx-android/*/build/reports/lint-results*.xml

notifications:
  email: false