name: Android CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      - run: chmod +x gradlew
      - run: gem install bundler
      - run: bundler install
    - name: Static Analysis
      - run: ./gradlew clean check assembleDebug assembleRelease --continue --stacktrace --parallel
      - run: fastlane android test
